<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    </PropertyGroup>

    <ItemGroup>
        <Folder Include="Assets\Fonts\"/>
        <Folder Include="Models\"/>
        <AvaloniaResource Include="Assets\**"/>
        <Folder Include="Screens\"/>
    </ItemGroup>

    <ItemGroup>
        <Compile Update="Views\KassaWindow.axaml.cs">
            <DependentUpon>KassaWindow.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Resources\ConfigFileDeafultContext.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>ConfigFileDeafultContext.resx</DependentUpon>
        </Compile>
        <Compile Update="Resources\ErrorMessages.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>ErrorMessages.resx</DependentUpon>
        </Compile>
        <Compile Update="Resources\UserInterface.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>UserInterface.resx</DependentUpon>
        </Compile>
        <Compile Update="Views\Screens\AuthorizationScreenView.axaml.cs">
            <DependentUpon>AuthorizationScreenView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Screens\MainConsoleScreenView.axaml.cs">
            <DependentUpon>MainConsoleScreenView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Resources\StoredProcedures.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>StoredProcedures.resx</DependentUpon>
        </Compile>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.1.1"/>
        <PackageReference Include="Avalonia.Desktop" Version="11.1.1"/>
        <PackageReference Include="Avalonia.Diagnostics" Version="11.1.1"/>
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.1.1"/>
        <PackageReference Include="Avalonia.ReactiveUI" Version="11.1.1"/>
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.1.1"/>
        <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.0"/>
        <PackageReference Include="System.Data.SqlClient" Version="4.8.6"/>
        <PackageReference Include="System.ServiceProcess.ServiceController" Version="8.0.0"/>
    </ItemGroup>

    <ItemGroup>
        <None Update="appsettings.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Update="Resources\ConfigFileDeafultContext.resx">
            <Generator>PublicResXFileCodeGenerator</Generator>
            <LastGenOutput>ConfigFileDeafultContext.Designer.cs</LastGenOutput>
            <LogicalName>Duckie2Client.Resources.ConfigFileDeafultContext.resources</LogicalName>
        </EmbeddedResource>
        <EmbeddedResource Update="Resources\ErrorMessages.resx">
            <Generator>PublicResXFileCodeGenerator</Generator>
            <LastGenOutput>ErrorMessages.Designer.cs</LastGenOutput>
            <LogicalName>Duckie2Client.Resources.ErrorMessages.resources</LogicalName>
        </EmbeddedResource>
        <EmbeddedResource Update="Resources\ErrorMessages.en.resx">
            <DependentUpon>ErrorMessages.resx</DependentUpon>
        </EmbeddedResource>
        <EmbeddedResource Update="Resources\ErrorMessages.en-us.resx">
            <DependentUpon>ErrorMessages.resx</DependentUpon>
        </EmbeddedResource>
        <EmbeddedResource Update="Resources\ErrorMessages.ru.resx">
            <DependentUpon>ErrorMessages.resx</DependentUpon>
        </EmbeddedResource>
        <EmbeddedResource Update="Resources\ErrorMessages.ru-ru.resx">
            <DependentUpon>ErrorMessages.resx</DependentUpon>
        </EmbeddedResource>
        <EmbeddedResource Update="Resources\UserInterface.resx">
            <Generator>PublicResXFileCodeGenerator</Generator>
            <LastGenOutput>UserInterface.Designer.cs</LastGenOutput>
            <LogicalName>Duckie2Client.Resources.UserInterface.resources</LogicalName>
        </EmbeddedResource>
        <EmbeddedResource Update="Resources\UserInterface.en.resx">
            <DependentUpon>UserInterface.resx</DependentUpon>
        </EmbeddedResource>
        <EmbeddedResource Update="Resources\UserInterface.en-us.resx">
            <DependentUpon>UserInterface.resx</DependentUpon>
        </EmbeddedResource>
        <EmbeddedResource Update="Resources\UserInterface.ru.resx">
            <DependentUpon>UserInterface.resx</DependentUpon>
        </EmbeddedResource>
        <EmbeddedResource Update="Resources\UserInterface.ru-ru.resx">
            <DependentUpon>UserInterface.resx</DependentUpon>
        </EmbeddedResource>
        <EmbeddedResource Update="Resources\StoredProcedures.resx">
            <Generator>ResXFileCodeGenerator</Generator>
            <LastGenOutput>StoredProcedures.Designer.cs</LastGenOutput>
        </EmbeddedResource>
    </ItemGroup>
</Project>
