<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    </PropertyGroup>

    <ItemGroup>
        <Folder Include="Assets\Fonts\"/>
        <Folder Include="Controls\Kassa\"/>
        <AvaloniaResource Include="Assets\**"/>
        <Folder Include="Migrations\"/>
        <Folder Include="Packages\"/>
        <Folder Include="Screens\"/>
        <Folder Include="ViewModels\Controls\"/>
        <Folder Include="Views\Screens\Kassa\"/>
    </ItemGroup>

    <ItemGroup>
        <Compile Update="Views\KassaWindow.axaml.cs">
            <DependentUpon>KassaWindow.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Resources\ConfigFileDeafultContext.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>ConfigFileDeafultContext.resx</DependentUpon>
        </Compile>
        <Compile Update="Resources\ErrorMessages.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>ErrorMessages.resx</DependentUpon>
        </Compile>
        <Compile Update="Resources\UserInterface.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>UserInterface.resx</DependentUpon>
        </Compile>
        <Compile Update="Views\Screens\AuthorizationScreenView.axaml.cs">
            <DependentUpon>AuthorizationScreenView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Screens\MainConsoleScreenView.axaml.cs">
            <DependentUpon>MainConsoleScreenView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Dialogs\SpinnerDialog.axaml.cs">
            <DependentUpon>SpinnerDialog.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Controls\Console\StartupControl.axaml.cs">
            <DependentUpon>Startup.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Screens\ManagerConsole\ClientCardBatchAddScreenView.axaml.cs">
            <DependentUpon>ClientCardBatchAddScreenScreenView.axaml</DependentUpon>
        </Compile>
        <Compile Update="App.axaml.declarations.cs">
            <DependentUpon>App.axaml</DependentUpon>
        </Compile>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.1.3"/>
        <PackageReference Include="Avalonia.Controls.DataGrid" Version="11.1.3"/>
        <PackageReference Include="Avalonia.Controls.ItemsRepeater" Version="11.1.3"/>
        <PackageReference Include="Avalonia.Desktop" Version="11.1.3"/>
        <PackageReference Include="Avalonia.Diagnostics" Version="11.1.3"/>
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.1.3"/>
        <PackageReference Include="Avalonia.ReactiveUI" Version="11.1.3"/>
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.1.3"/>
        <PackageReference Include="Avalonia.Xaml.Behaviors" Version="11.1.0.4"/>
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.3.2"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.8"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.8">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.8"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.8">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.0"/>
        <PackageReference Include="ReactiveUI.Fody" Version="19.5.41"/>
        <PackageReference Include="Splat" Version="15.2.22"/>
        <PackageReference Include="Splat.DependencyInjection.SourceGenerator" Version="1.2.3">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="System.Data.Common" Version="4.3.0"/>
        <PackageReference Include="System.Data.SqlClient" Version="4.8.6"/>
        <PackageReference Include="System.ServiceProcess.ServiceController" Version="8.0.0"/>
        <PackageReference Include="Tabalonia" Version="0.10.4"/>
    </ItemGroup>

    <ItemGroup>
        <None Update="appsettings.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Remove="FodyWeavers.xml"/>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Update="Resources\ConfigFileDeafultContext.resx">
            <Generator>PublicResXFileCodeGenerator</Generator>
            <LastGenOutput>ConfigFileDeafultContext.Designer.cs</LastGenOutput>
            <LogicalName>Duckie2Client.Resources.ConfigFileDeafultContext.resources</LogicalName>
        </EmbeddedResource>
        <EmbeddedResource Update="Resources\ErrorMessages.resx">
            <Generator>PublicResXFileCodeGenerator</Generator>
            <LastGenOutput>ErrorMessages.Designer.cs</LastGenOutput>
            <LogicalName>Duckie2Client.Resources.ErrorMessages.resources</LogicalName>
        </EmbeddedResource>
        <EmbeddedResource Update="Resources\ErrorMessages.en.resx">
            <DependentUpon>ErrorMessages.resx</DependentUpon>
        </EmbeddedResource>
        <EmbeddedResource Update="Resources\ErrorMessages.en-us.resx">
            <DependentUpon>ErrorMessages.resx</DependentUpon>
        </EmbeddedResource>
        <EmbeddedResource Update="Resources\ErrorMessages.ru.resx">
            <DependentUpon>ErrorMessages.resx</DependentUpon>
        </EmbeddedResource>
        <EmbeddedResource Update="Resources\ErrorMessages.ru-ru.resx">
            <DependentUpon>ErrorMessages.resx</DependentUpon>
        </EmbeddedResource>
        <EmbeddedResource Update="Resources\UserInterface.resx">
            <Generator>PublicResXFileCodeGenerator</Generator>
            <LastGenOutput>UserInterface.Designer.cs</LastGenOutput>
            <LogicalName>Duckie2Client.Resources.UserInterface.resources</LogicalName>
        </EmbeddedResource>
        <EmbeddedResource Update="Resources\UserInterface.en.resx">
            <DependentUpon>UserInterface.resx</DependentUpon>
        </EmbeddedResource>
        <EmbeddedResource Update="Resources\UserInterface.en-us.resx">
            <DependentUpon>UserInterface.resx</DependentUpon>
        </EmbeddedResource>
        <EmbeddedResource Update="Resources\UserInterface.ru.resx">
            <DependentUpon>UserInterface.resx</DependentUpon>
        </EmbeddedResource>
        <EmbeddedResource Update="Resources\UserInterface.ru-ru.resx">
            <DependentUpon>UserInterface.resx</DependentUpon>
        </EmbeddedResource>
    </ItemGroup>


    <ItemGroup>
        <Reference Include="DialogHost.Avalonia">
            <HintPath>Packages\DialogHost.Avalonia.dll</HintPath>
        </Reference>
        <Reference Include="System.Xaml"/>
    </ItemGroup>


    <ItemGroup>
        <ProjectReference Include="..\DataFaker\DataFaker.csproj"/>
    </ItemGroup>
</Project>
