// <auto-generated />
using System;
using Duckie2Client.Services.DbmsService;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Duckie2Client.Migrations
{
    [DbContext(typeof(DbmsService))]
    [Migration("20240924110049_InitialCreate3")]
    partial class InitialCreate3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClientVehicle", b =>
                {
                    b.Property<Guid>("ClientsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VehiclesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ClientsId", "VehiclesId");

                    b.HasIndex("VehiclesId");

                    b.ToTable("ClientVehicle");
                });

            modelBuilder.Entity("Duckie2Client.Models.Database.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR");

                    b.HasKey("Id");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("Duckie2Client.Models.Database.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR");

                    b.Property<DateTime>("FirstRegistration")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Duckie2Client.Models.Database.ClientBonus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Summa")
                        .HasColumnType("DECIMAL(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.ToTable("ClientBonuses");
                });

            modelBuilder.Entity("Duckie2Client.Models.Database.CommunicationMean", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasMaxLength(512)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("UserId");

                    b.ToTable("CommunicationMeans");
                });

            modelBuilder.Entity("Duckie2Client.Models.Database.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("RegistrationNumber")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Duckie2Client.Models.Database.LegacyCompany", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Код");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NCHAR")
                        .HasColumnName("Адрес");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Наименование");

                    b.HasKey("CompanyId");

                    b.ToTable("Фирмы");
                });

            modelBuilder.Entity("Duckie2Client.Models.Database.LegacyVehicle", b =>
                {
                    b.Property<string>("Licence")
                        .HasMaxLength(10)
                        .HasColumnType("NCHAR")
                        .HasColumnName("Номер");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("КодФирмы");

                    b.Property<decimal>("Discount")
                        .HasColumnType("DECIMAL(2,2)")
                        .HasColumnName("Скидка");

                    b.Property<string>("PriceCategory")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("NCHAR")
                        .HasColumnName("Категория");

                    b.Property<Guid>("new_id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Licence");

                    b.ToTable("Транспорт");
                });

            modelBuilder.Entity("Duckie2Client.Models.Database.PollutionLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("NVARCHAR");

                    b.HasKey("Id");

                    b.ToTable("PollutionLevels");
                });

            modelBuilder.Entity("Duckie2Client.Models.Database.PriceType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id");

                    b.ToTable("PriceTypes");
                });

            modelBuilder.Entity("Duckie2Client.Models.Database.Rate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Rates");
                });

            modelBuilder.Entity("Duckie2Client.Models.Database.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR");

                    b.Property<bool>("IsStaff")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("VARCHAR");

                    b.Property<DateOnly>("RegistrationDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("SalaryRateId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("SalaryRateId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Duckie2Client.Models.Database.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Licence")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.Property<Guid>("PriceTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Licence")
                        .IsUnique();

                    b.HasIndex("PriceTypeId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("ClientVehicle", b =>
                {
                    b.HasOne("Duckie2Client.Models.Database.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Duckie2Client.Models.Database.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehiclesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Duckie2Client.Models.Database.ClientBonus", b =>
                {
                    b.HasOne("Duckie2Client.Models.Database.Client", null)
                        .WithOne("Bonus")
                        .HasForeignKey("Duckie2Client.Models.Database.ClientBonus", "ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Duckie2Client.Models.Database.CommunicationMean", b =>
                {
                    b.HasOne("Duckie2Client.Models.Database.Client", "Client")
                        .WithMany("CommunicationMeans")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Duckie2Client.Models.Database.User", null)
                        .WithMany("Communication")
                        .HasForeignKey("UserId");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Duckie2Client.Models.Database.User", b =>
                {
                    b.HasOne("Duckie2Client.Models.Database.Branch", "Branch")
                        .WithMany("Users")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Duckie2Client.Models.Database.Rate", "SalaryRate")
                        .WithMany()
                        .HasForeignKey("SalaryRateId");

                    b.Navigation("Branch");

                    b.Navigation("SalaryRate");
                });

            modelBuilder.Entity("Duckie2Client.Models.Database.Vehicle", b =>
                {
                    b.HasOne("Duckie2Client.Models.Database.Company", null)
                        .WithMany("Vehicles")
                        .HasForeignKey("CompanyId");

                    b.HasOne("Duckie2Client.Models.Database.PriceType", "PriceType")
                        .WithMany()
                        .HasForeignKey("PriceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PriceType");
                });

            modelBuilder.Entity("Duckie2Client.Models.Database.Branch", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Duckie2Client.Models.Database.Client", b =>
                {
                    b.Navigation("Bonus")
                        .IsRequired();

                    b.Navigation("CommunicationMeans");
                });

            modelBuilder.Entity("Duckie2Client.Models.Database.Company", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("Duckie2Client.Models.Database.User", b =>
                {
                    b.Navigation("Communication");
                });
#pragma warning restore 612, 618
        }
    }
}
