// <auto-generated />
using System;
using Duckie2Client.Services.DbmsService;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Duckie2Client.Migrations
{
    [DbContext(typeof(DbmsService))]
    partial class DbmsServiceModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BranchUser", b =>
                {
                    b.Property<Guid>("BranchesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BranchesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("BranchUser");
                });

            modelBuilder.Entity("ClientVehicle", b =>
                {
                    b.Property<Guid>("ClientsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VehiclesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ClientsId", "VehiclesId");

                    b.HasIndex("VehiclesId");

                    b.ToTable("ClientVehicle");
                });

            modelBuilder.Entity("Duckie2Client.Models.Database.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR");

                    b.HasKey("Id");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("Duckie2Client.Models.Database.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR");

                    b.Property<DateTime>("FirstRegistration")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Duckie2Client.Models.Database.ClientBonus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Summa")
                        .HasColumnType("DECIMAL(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.ToTable("ClientBonuses");
                });

            modelBuilder.Entity("Duckie2Client.Models.Database.CommunicationMean", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasMaxLength(512)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("UserId");

                    b.ToTable("CommunicationMeans");
                });

            modelBuilder.Entity("Duckie2Client.Models.Database.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("RegistrationNumber")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Duckie2Client.Models.Database.PollutionLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("NVARCHAR");

                    b.HasKey("Id");

                    b.ToTable("PollutionLevels");
                });

            modelBuilder.Entity("Duckie2Client.Models.Database.Price", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PriceTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ValueId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PriceTypeId");

                    b.HasIndex("ValueId");

                    b.ToTable("Prices");
                });

            modelBuilder.Entity("Duckie2Client.Models.Database.PriceType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id");

                    b.ToTable("PriceTypes");
                });

            modelBuilder.Entity("Duckie2Client.Models.Database.Rate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<decimal>("Value")
                        .HasColumnType("DECIMAL(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Rates");
                });

            modelBuilder.Entity("Duckie2Client.Models.Database.TradeUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsGood")
                        .HasColumnType("bit");

                    b.Property<bool>("IsIgnoreDiscounts")
                        .HasColumnType("bit");

                    b.Property<TimeOnly?>("ProcessTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("TradeUnits");
                });

            modelBuilder.Entity("Duckie2Client.Models.Database.TradeUnitLocalization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("VARCHAR");

                    b.Property<Guid?>("TradeUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR");

                    b.HasKey("Id");

                    b.HasIndex("TradeUnitId");

                    b.ToTable("TradeUnitLocalizations");
                });

            modelBuilder.Entity("Duckie2Client.Models.Database.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsStaff")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("VARCHAR");

                    b.Property<DateOnly>("RegistrationDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Duckie2Client.Models.Database.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Licence")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.Property<Guid>("PriceTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Licence")
                        .IsUnique();

                    b.HasIndex("PriceTypeId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("Duckie2Client.Models.Database.Wash", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("BonusesUses")
                        .HasColumnType("DECIMAL(10,2)");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentType")
                        .HasColumnType("int");

                    b.Property<Guid?>("PollutionLevelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReceiptNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("VehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("ClientId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("PollutionLevelId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Washes");
                });

            modelBuilder.Entity("PollutionLevelRate", b =>
                {
                    b.Property<Guid>("PollutionLevelsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RatesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PollutionLevelsId", "RatesId");

                    b.HasIndex("RatesId");

                    b.ToTable("PollutionLevelRate");
                });

            modelBuilder.Entity("PriceTradeUnit", b =>
                {
                    b.Property<Guid>("PricesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TradeUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PricesId", "TradeUnitId");

                    b.HasIndex("TradeUnitId");

                    b.ToTable("PriceTradeUnit");
                });

            modelBuilder.Entity("RateUser", b =>
                {
                    b.Property<Guid>("SalaryRatesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SalaryRatesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("RateUser");
                });

            modelBuilder.Entity("TradeUnitWash", b =>
                {
                    b.Property<Guid>("TradeUnitsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WashesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TradeUnitsId", "WashesId");

                    b.HasIndex("WashesId");

                    b.ToTable("TradeUnitWash");
                });

            modelBuilder.Entity("BranchUser", b =>
                {
                    b.HasOne("Duckie2Client.Models.Database.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Duckie2Client.Models.Database.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClientVehicle", b =>
                {
                    b.HasOne("Duckie2Client.Models.Database.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Duckie2Client.Models.Database.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehiclesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Duckie2Client.Models.Database.ClientBonus", b =>
                {
                    b.HasOne("Duckie2Client.Models.Database.Client", null)
                        .WithOne("Bonus")
                        .HasForeignKey("Duckie2Client.Models.Database.ClientBonus", "ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Duckie2Client.Models.Database.CommunicationMean", b =>
                {
                    b.HasOne("Duckie2Client.Models.Database.Client", null)
                        .WithMany("CommunicationMeans")
                        .HasForeignKey("ClientId");

                    b.HasOne("Duckie2Client.Models.Database.User", null)
                        .WithMany("Communication")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Duckie2Client.Models.Database.Price", b =>
                {
                    b.HasOne("Duckie2Client.Models.Database.PriceType", "PriceType")
                        .WithMany()
                        .HasForeignKey("PriceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Duckie2Client.Models.Database.Rate", "Value")
                        .WithMany()
                        .HasForeignKey("ValueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PriceType");

                    b.Navigation("Value");
                });

            modelBuilder.Entity("Duckie2Client.Models.Database.TradeUnitLocalization", b =>
                {
                    b.HasOne("Duckie2Client.Models.Database.TradeUnit", null)
                        .WithMany("Names")
                        .HasForeignKey("TradeUnitId");
                });

            modelBuilder.Entity("Duckie2Client.Models.Database.Vehicle", b =>
                {
                    b.HasOne("Duckie2Client.Models.Database.Company", null)
                        .WithMany("Vehicles")
                        .HasForeignKey("CompanyId");

                    b.HasOne("Duckie2Client.Models.Database.PriceType", "PriceType")
                        .WithMany()
                        .HasForeignKey("PriceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PriceType");
                });

            modelBuilder.Entity("Duckie2Client.Models.Database.Wash", b =>
                {
                    b.HasOne("Duckie2Client.Models.Database.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Duckie2Client.Models.Database.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId");

                    b.HasOne("Duckie2Client.Models.Database.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.HasOne("Duckie2Client.Models.Database.PollutionLevel", "PollutionLevel")
                        .WithMany()
                        .HasForeignKey("PollutionLevelId");

                    b.HasOne("Duckie2Client.Models.Database.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId");

                    b.Navigation("Branch");

                    b.Navigation("Client");

                    b.Navigation("Company");

                    b.Navigation("PollutionLevel");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("PollutionLevelRate", b =>
                {
                    b.HasOne("Duckie2Client.Models.Database.PollutionLevel", null)
                        .WithMany()
                        .HasForeignKey("PollutionLevelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Duckie2Client.Models.Database.Rate", null)
                        .WithMany()
                        .HasForeignKey("RatesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PriceTradeUnit", b =>
                {
                    b.HasOne("Duckie2Client.Models.Database.Price", null)
                        .WithMany()
                        .HasForeignKey("PricesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Duckie2Client.Models.Database.TradeUnit", null)
                        .WithMany()
                        .HasForeignKey("TradeUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RateUser", b =>
                {
                    b.HasOne("Duckie2Client.Models.Database.Rate", null)
                        .WithMany()
                        .HasForeignKey("SalaryRatesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Duckie2Client.Models.Database.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TradeUnitWash", b =>
                {
                    b.HasOne("Duckie2Client.Models.Database.TradeUnit", null)
                        .WithMany()
                        .HasForeignKey("TradeUnitsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Duckie2Client.Models.Database.Wash", null)
                        .WithMany()
                        .HasForeignKey("WashesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Duckie2Client.Models.Database.Client", b =>
                {
                    b.Navigation("Bonus");

                    b.Navigation("CommunicationMeans");
                });

            modelBuilder.Entity("Duckie2Client.Models.Database.Company", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("Duckie2Client.Models.Database.TradeUnit", b =>
                {
                    b.Navigation("Names");
                });

            modelBuilder.Entity("Duckie2Client.Models.Database.User", b =>
                {
                    b.Navigation("Communication");
                });
#pragma warning restore 612, 618
        }
    }
}
