//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duckie2Client.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Duckie2Client.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;no translation&gt;.
        /// </summary>
        public static string _101_ArgumentInvalidNumber {
            get {
                return ResourceManager.GetString("101_ArgumentInvalidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;no translation&gt;.
        /// </summary>
        public static string _102_ArgumentsHaveNoOption {
            get {
                return ResourceManager.GetString("102_ArgumentsHaveNoOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;no translation&gt;.
        /// </summary>
        public static string _103_OptionInvalidName {
            get {
                return ResourceManager.GetString("103_OptionInvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;no translation&gt;.
        /// </summary>
        public static string _104_InvalidOptionValue {
            get {
                return ResourceManager.GetString("104_InvalidOptionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;no translation&gt;.
        /// </summary>
        public static string _105_ApplicationInstanceAlreadyExists {
            get {
                return ResourceManager.GetString("105_ApplicationInstanceAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;no translation&gt;.
        /// </summary>
        public static string _106_UnknownAppMode {
            get {
                return ResourceManager.GetString("106_UnknownAppMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;no translation&gt;.
        /// </summary>
        public static string _201_DbConnectionInvalid {
            get {
                return ResourceManager.GetString("201_DbConnectionInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;no translation&gt;.
        /// </summary>
        public static string _202_DbServiceUnavailable {
            get {
                return ResourceManager.GetString("202_DbServiceUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;no translation&gt;.
        /// </summary>
        public static string _203_DbServiceStopped {
            get {
                return ResourceManager.GetString("203_DbServiceStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;no translation&gt;.
        /// </summary>
        public static string _204_DbServicePaused {
            get {
                return ResourceManager.GetString("204_DbServicePaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;no translation&gt;.
        /// </summary>
        public static string _205_TargetDbDoesNotExist {
            get {
                return ResourceManager.GetString("205_TargetDbDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;no translation&gt;.
        /// </summary>
        public static string _301_UserHasNoAccessRights {
            get {
                return ResourceManager.GetString("301_UserHasNoAccessRights", resourceCulture);
            }
        }
    }
}
