//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duckie2Client.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UserInterface {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserInterface() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Duckie2Client.Resources.UserInterface", typeof(UserInterface).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;no translation&gt;.
        /// </summary>
        public static string ConfigFileChecking {
            get {
                return ResourceManager.GetString("ConfigFileChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;no translation&gt;.
        /// </summary>
        public static string ConfigFileValid {
            get {
                return ResourceManager.GetString("ConfigFileValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;no translation&gt;.
        /// </summary>
        public static string DatabaseConnectionCheck {
            get {
                return ResourceManager.GetString("DatabaseConnectionCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;no translation&gt;.
        /// </summary>
        public static string DBMSServiceRunCheck {
            get {
                return ResourceManager.GetString("DBMSServiceRunCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;no translation&gt;.
        /// </summary>
        public static string DBMSServiceRunCheckSuccess {
            get {
                return ResourceManager.GetString("DBMSServiceRunCheckSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;no translation&gt;.
        /// </summary>
        public static string LoadingProcessDone {
            get {
                return ResourceManager.GetString("LoadingProcessDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;no translation&gt;.
        /// </summary>
        public static string TabDataLoadingStateBranchList {
            get {
                return ResourceManager.GetString("TabDataLoadingStateBranchList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;no translation&gt;.
        /// </summary>
        public static string TabDataLoadingStateClientList {
            get {
                return ResourceManager.GetString("TabDataLoadingStateClientList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;no translation&gt;.
        /// </summary>
        public static string TabDataLoadingStateCompanyList {
            get {
                return ResourceManager.GetString("TabDataLoadingStateCompanyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;no translation&gt;.
        /// </summary>
        public static string TabDataLoadingStatePersonnelList {
            get {
                return ResourceManager.GetString("TabDataLoadingStatePersonnelList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;no translation&gt;.
        /// </summary>
        public static string TabDataLoadingStatePollutionList {
            get {
                return ResourceManager.GetString("TabDataLoadingStatePollutionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;no translation&gt;.
        /// </summary>
        public static string TabDataLoadingStatePriceTypeList {
            get {
                return ResourceManager.GetString("TabDataLoadingStatePriceTypeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;no translation&gt;.
        /// </summary>
        public static string TabDataLoadingStateTradeUnitList {
            get {
                return ResourceManager.GetString("TabDataLoadingStateTradeUnitList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;no translation&gt;.
        /// </summary>
        public static string TabReadyStateMessageBranchList {
            get {
                return ResourceManager.GetString("TabReadyStateMessageBranchList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;no translation&gt;.
        /// </summary>
        public static string TabReadyStateMessageClientList {
            get {
                return ResourceManager.GetString("TabReadyStateMessageClientList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;no translation&gt;.
        /// </summary>
        public static string TabReadyStateMessageCompanyList {
            get {
                return ResourceManager.GetString("TabReadyStateMessageCompanyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;no translation&gt;.
        /// </summary>
        public static string TabReadyStateMessagePersonnelList {
            get {
                return ResourceManager.GetString("TabReadyStateMessagePersonnelList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;no translation&gt;.
        /// </summary>
        public static string TabReadyStateMessagePollutionList {
            get {
                return ResourceManager.GetString("TabReadyStateMessagePollutionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;no translation&gt;.
        /// </summary>
        public static string TabReadyStateMessagePriceTypeList {
            get {
                return ResourceManager.GetString("TabReadyStateMessagePriceTypeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;no translation&gt;.
        /// </summary>
        public static string TabReadyStateMessageTradeUnitList {
            get {
                return ResourceManager.GetString("TabReadyStateMessageTradeUnitList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;no translation&gt;.
        /// </summary>
        public static string TabTitleBranchList {
            get {
                return ResourceManager.GetString("TabTitleBranchList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;no translation&gt;.
        /// </summary>
        public static string TabTitleClientList {
            get {
                return ResourceManager.GetString("TabTitleClientList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;no translation&gt;.
        /// </summary>
        public static string TabTitleCompanyList {
            get {
                return ResourceManager.GetString("TabTitleCompanyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;no translation&gt;.
        /// </summary>
        public static string TabTitlePersonnelList {
            get {
                return ResourceManager.GetString("TabTitlePersonnelList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;no translation&gt;.
        /// </summary>
        public static string TabTitlePollutionList {
            get {
                return ResourceManager.GetString("TabTitlePollutionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;no translation&gt;.
        /// </summary>
        public static string TabTitlePriceTypeList {
            get {
                return ResourceManager.GetString("TabTitlePriceTypeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;no translation&gt;.
        /// </summary>
        public static string TabTitleTradeUnitList {
            get {
                return ResourceManager.GetString("TabTitleTradeUnitList", resourceCulture);
            }
        }
    }
}
